version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: medflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db  
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - medflow-network
volumes:
  mongodb-data: 

networks:
  medflow-network:
    driver: bridge