version: "3.8"

services:
  web:
    # Use the repo root as the build context.
    build:
      context: .
      # This is your existing Dockerfile for the web app.
      dockerfile: apps/web/Dockerfile
      # Forward the build arguments your Dockerfile expects.
      args:
        MONGODB_URI: ${MONGODB_URI}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        DO_SPACES_CDN_ENDPOINT: ${DO_SPACES_CDN_ENDPOINT}
        DO_SPACES_BUCKET: ${DO_SPACES_BUCKET}
        DO_SPACES_ENDPOINT: ${DO_SPACES_ENDPOINT}
        DO_SPACES_KEY: ${DO_SPACES_KEY}
        DO_SPACES_REGION: ${DO_SPACES_REGION}
        DO_SPACES_SECRET: ${DO_SPACES_SECRET}
        GMAIL_SENDER_EMAIL: ${GMAIL_SENDER_EMAIL}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        MEDFLOW_KEY: ${MEDFLOW_KEY}
        MEDFLOW_SENDGRID_KEY: ${MEDFLOW_SENDGRID_KEY}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
        NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
        NODE_ENV: ${NODE_ENV}
    # Pass these same variables into the container at runtime.
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGODB_URI: ${MONGODB_URI}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      DO_SPACES_CDN_ENDPOINT: ${DO_SPACES_CDN_ENDPOINT}
      DO_SPACES_BUCKET: ${DO_SPACES_BUCKET}
      DO_SPACES_ENDPOINT: ${DO_SPACES_ENDPOINT}
      DO_SPACES_KEY: ${DO_SPACES_KEY}
      DO_SPACES_REGION: ${DO_SPACES_REGION}
      DO_SPACES_SECRET: ${DO_SPACES_SECRET}
      GMAIL_SENDER_EMAIL: ${GMAIL_SENDER_EMAIL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      MEDFLOW_KEY: ${MEDFLOW_KEY}
      MEDFLOW_SENDGRID_KEY: ${MEDFLOW_SENDGRID_KEY}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
    ports:
      # Adjust these ports as needed (make sure Coolify’s port mappings agree)
      - "3001:3001"