name: Deploy to Coolify

on:
  push:
    branches:
      - main  # Make sure this matches your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST -H "Content-Type: application/json" \
               -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
               -d '{"action":"deploy"}' \
               "http://188.245.253.95:8000/api/v1/deploy?uuid=fwosc08k4w4sw08ogk4kkko4&force=false"